### ISSUE TITLE
OSX Retina Display not handled correctly

### ISSUE THREAD

**Issue by sethjohnson** [ivlab/MinVR2#103]
Graphics apps only fill the bottom-left quarter of the window on Retina-Display macs, since for a 800x800 window, a 1600x1600 Framebuffer is created. 

<img width="640" alt="screen shot 2017-01-25 at 3 54 14 pm" src="https://cloud.githubusercontent.com/assets/307029/22310910/8f5bd670-e316-11e6-8156-5da78f18958d.png">

**Comment by sethjohnson** [comment]
@dtorban thinks he has a solution to this

**Comment by dtorban** [comment]
Bret has fixed this before, I'll see how he did it.

**Comment by dtorban** [comment]
Seth, can you build the beta branch and run the following command:
```bash
build/bin/itest-opengl-shaderpipeline -c desktop
```
Can you verify that the viewport is set correctly or not on your display?
