### ISSUE TITLE
Issue in VRFakeTrackerDevice on Linux

### ISSUE THREAD

**Issue by dtorban** [ivlab/MinVR2#111]
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp: In constructor ‘MinVR::VRFakeTrackerDevice::VRFakeTrackerDevice(const string&, const string&, float, float, float)’:
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:28:14: error: ‘TrackingState’ is not a class or namespace
     _state = TrackingState::XYTranslating;
              ^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp: In member function ‘virtual void MinVR::VRFakeTrackerDevice::onVREvent(const MinVR::VREvent&)’:
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:44:22: error: ‘TrackingState’ is not a class or namespace
             _state = TrackingState::XYTranslating;
                      ^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:48:18: error: ‘TrackingState’ is not a class or namespace
         _state = TrackingState::ZTranslating;
                  ^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:51:18: error: ‘TrackingState’ is not a class or namespace
         _state = TrackingState::XYTranslating;
                  ^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:54:18: error: ‘TrackingState’ is not a class or namespace
         _state = TrackingState::Rotating;
                  ^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:57:18: error: ‘TrackingState’ is not a class or namespace
         _state = TrackingState::XYTranslating;
                  ^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:70:31: error: ‘TrackingState’ is not a class or namespace
                 if (_state == TrackingState::ZTranslating) {
                               ^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:73:36: error: ‘TrackingState’ is not a class or namespace
                 else if (_state == TrackingState::Rotating) {

**Comment by dankeefe** [comment]
Try the pull request just submitted.
d


On February 17, 2017 at 1:05:32 PM, dtorban (notifications@github.com) wrote:

/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp: In constructor ‘MinVR::VRFakeTrackerDevice::VRFakeTrackerDevice(const string&, const string&, float, float, float)’:
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:28:14: error: ‘TrackingState’ is not a class or namespace
_state = TrackingState::XYTranslating;
^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp: In member function ‘virtual void MinVR::VRFakeTrackerDevice::onVREvent(const MinVR::VREvent&)’:
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:44:22: error: ‘TrackingState’ is not a class or namespace
_state = TrackingState::XYTranslating;
^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:48:18: error: ‘TrackingState’ is not a class or namespace
_state = TrackingState::ZTranslating;
^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:51:18: error: ‘TrackingState’ is not a class or namespace
_state = TrackingState::XYTranslating;
^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:54:18: error: ‘TrackingState’ is not a class or namespace
_state = TrackingState::Rotating;
^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:57:18: error: ‘TrackingState’ is not a class or namespace
_state = TrackingState::XYTranslating;
^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:70:31: error: ‘TrackingState’ is not a class or namespace
if (_state == TrackingState::ZTranslating) {
^
/home/dan/src/MinVR2/src/input/VRFakeTrackerDevice.cpp:73:36: error: ‘TrackingState’ is not a class or namespace
else if (_state == TrackingState::Rotating) {
