### ISSUE TITLE
Need safe way to copy VRDataIndex

### ISSUE THREAD

**Issue by dtorban** [ivlab/MinVR2#135]
For multithreading, we need a safe way to copy a data index so each threaded node can work on it's own copy for the render state.  Right now if I use the default copy constructor it will copy the data map dictionary which contains a bunch of pointers, so the copy will have the same pointers, which means multiple threads will be pushing and popping the same values for the state.  This is not what we want in a multithreaded approach, as the data should be copies, not the same data itself.

**Comment by tsgouros** [comment]
Inside the data index, the data map (level 1) contains pointers to VRDatum objects (level 2), which contain pointers to data (level 3). The level 3 data is never changed, though there is a stack for the level 2 pointers to implement the pushing and popping.

How deep does the copy have to go to be safe?

**Comment by dtorban** [comment]
Tom, I'm not completely sure, but the VRDatum object pointers as well as their pushing and popping need to be separate objects, so maybe if the VRDatum object was able to clone itself to a new object that would work.  Is that levels 1, 2, and 3, or just 1 and 2?  Threads need to be able to simultaneously push and pop.

**Comment by tsgouros** [comment]
Implemented a deep copy constructor for the data index. This is included in pull request #151.

**Comment by tsgouros** [comment]
Dan points out he'd like to test and merge this before closing. Suppose that's a better idea.

**Comment by tsgouros** [comment]
Closing because it's done and the issues list is for things that need doing. If Dan finds it doesn't work, he can reopen.
