### ISSUE TITLE
Missing VRCoreTypes.h

### ISSUE THREAD

**Issue by dtorban** [ivlab/MinVR2#14]
I got the following error while building config:

MinVR2/config/VRDatum.h:19:25: fatal error: VRCoreTypes.h: No such file or directory
 #include "VRCoreTypes.h"

**Comment by dankeefe** [comment]
We might have some build errors for the next week or so in master as we all
sync up.  Let's take our time as needed to work through these.  Then once
we reach a steady state start treating the master as a sacred place.

On Friday, December 11, 2015, dtorban notifications@github.com wrote:

> I got the following error while building config:
> 
> MinVR2/config/VRDatumh:19:25: fatal error: VRCoreTypesh: No such file or
> directory
> #include "VRCoreTypesh"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ivlab/MinVR2/issues/14.

## 

Daniel Keefe
Associate Professor
Department of Computer Science and Engineering
University of Minnesota
http://www.cs.umn.edu/~keefe/

**Comment by tsgouros** [comment]
I just forgot to add VRCoreTypes.h before committing the change. I've added it since, but I haven't pushed it back to the repo and won't until I can clear up the config/data thing, because I don't have a working build. Working on it now.

**Comment by dtorban** [comment]
Cool, sounds good!  Take your time.

**Comment by tsgouros** [comment]
It's in the pull request I just made.

**Comment by tsgouros** [comment]
Reopened, but assigned to Dan O who can decide who approves or rejects my pull request.
