### ISSUE TITLE
Win DLL file locations

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#159]
For example, the OpenVR MinVR plugin needs to have access to the OpenVR DLL file. Many people (apparently) do not have this installed system-wide, so need the DLL copied into the directory where the executable will reside. Am I misunderstanding this?

Propose that each plugin copy the DLLs it needs into somewhere in the install tree.  Something like $INSTALL/share/dlls or something, so a build script can copy stuff from there. Or someone else have something to propose?

**Comment by dtorban** [comment]
I could be wrong, but I'm pretty sure that the OpenVR DLL needs to be
copied to the application's bin directory where the user application is
built.  If so, the copy would need to be on the MinVR library user side.
On the other hand, perhaps the DLL only needs to be copied to the same
directory as the plugin dll, which means we can handle on the MinVR side of
things.  I'm open to being wrong :).

Thanks,
Dan

**Comment by tsgouros** [comment]
I think you're right about that, but I thought that if the MinVR install accumulated those DLLs into a single directory then another application that linked to MinVR could have its install routine move all the contents of that directory to the final application bin directory.

**Comment by dtorban** [comment]
Oh, that's a good idea.  Makes sense now.

Thanks,
Dan

**Comment by tsgouros** [comment]
This may be addressed with pull request #206. Leaving it up to Bret to decide.

**Comment by bretjackson** [comment]
I think this is now fixed by #206  so I'm closing it now.
