### ISSUE TITLE
cmake cleanup

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#176]
One of the big things on my mind is to revisit the way we handle external dependencies for the plugins and make sure we are following best practices and our best ideas on that front.  And, also are being consistent on how we handle everything.  For example:

- We talked last week about maybe getting rid of the base plugins flag and just treat all plugins the same because we can never remember what is in the base and what is not.

- Adding instructional messages and hints to cmake so that it prints out info about the flags when you run it rather than having to dig into the cmakelists.txt files to figure out what options are possible.

- The auto download and build for external projects is awesome, but also potentially confusing because it is sort of hidden.  What if we:  1. Make it super clear how to provide your own path to a dependency prior to the build if you want.  2. If you don't provide your own path and so we do the auto download and build thing for you, we also assume that at some point you will want to be able to build and link your own code against this dependency.  This may not always be true, but if it is true, for example, if I had a haptics library that I wanted MinVR to build for me but that I needed to be able to access a pointer to and include headers in my own project, this would currently be very difficult.   I think it would be easier for this sort of thing if we put the source in a folder like MinVR/ext or MinVR/3rd-party rather than MinVR/build/..../..../....  (Which I think is the case now, although we may have already changed this, can't remember for sure.)  Also, when we do an install of MinVR, it should also install these dependencies.

- General clean up.  Cmake is a bit of a beast, and so we often copy and paste things together as we go... are there any places where have unnecessary cruft in these cmake files that we can clean up?

- Consistency checks / best practices.  For example, if I remember right, the src directory is built from the main cmakelists.txt file in MinVR/ and there is no cmakelists.txt inside src/ but other parts of the project have their own cmakelists.txt.  Maybe there is some cleanup that would be useful here.  What if the main cmakelists.txt just adds subdirs to build the lib, tests, plugins, (maybe examples), and then these all have their own cmakelists.txt with details inside themselves.

- Generate and install a cmake MinVR.findmodule file or whatever the latest mechanism cmake is using to support this.

Examples:
- Tom's cmakelists.txt that he created for the demo-graphic project are a great example of having cmake print out messages to tell you what it is up to.  

- I recently wrote a cmakelists.txt that I really liked for a proejct that is admittedly much, much simpler than MinVR, but I really liked how the file is organized into sections and includes comments to understand what is going on, etc.  It probably won't translate exactly to our situation, but might provide some inspiration, so attaching here.

- By the way, this last example of mine is for a project that uses the NanoGUI library, which has a pretty clean approach to building external dependencies inside an ext/ directory.  It also uses cmake messages to test to see if the dependency directories exist, and if they don't if gives you the hint that you should run git submodule --init --recursive to grab the depends.  This was a super helpful message, the kind of thing we should include for sure!!

**Comment by bretjackson** [comment]
During the cmake build process, each external dependency should download into a folder called external at the minvr  root level. There is already a 3rd-party/GLEW folder. It should be made to be consistent so that it also downloads like the others.

**Comment by bretjackson** [comment]
We should also modify the behavior to try to find dependencies on the system before downloading.

**Comment by tsgouros** [comment]
Should this be closed?

**Comment by tsgouros** [comment]
Closing this because it seems like lots of the cmake work this winter addressed it.
