### ISSUE TITLE
defensive programming around index->getValue();

### ISSUE THREAD

**Issue by dankeefe** [ivlab/MinVR2#178]
This seems like a useful optimization.  Consider potential for small changes that might help people to use use this correctly / prevent an accidental bug.  For example, maybe call it getCachedValue() to make it super clear that you need to have called exists() first in order to populate the cache.  And/or make the error message even more specific...  not sure what would be best.

**Comment by tsgouros** [comment]
Added advice to the VRERROR() message to make it clear that you have to call exists() first. Fixed in pull request #207
