### ISSUE TITLE
linux build (at least in branch feature-build-2) complaining that VRDataQueue.h requires C++11?

### ISSUE THREAD

**Issue by dankeefe** [ivlab/MinVR2#187]
jimmypage ~/G/src/MinVR/build -> make
Scanning dependencies of target MinVR
[  1%] Building CXX object CMakeFiles/MinVR.dir/src/config/VRDataIndex.cpp.o
[  3%] Building CXX object CMakeFiles/MinVR.dir/src/config/VRDataQueue.cpp.o
In file included from /usr/include/c++/5/type_traits:35:0,
                 from /home/fac07/keefe/G/src/MinVR/src/config/VRDataQueue.h:25,
                 from /home/fac07/keefe/G/src/MinVR/src/config/VRDataQueue.cpp:1:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
CMakeFiles/MinVR.dir/build.make:86: recipe for target 'CMakeFiles/MinVR.dir/src/config/VRDataQueue.cpp.o' failed
make[2]: *** [CMakeFiles/MinVR.dir/src/config/VRDataQueue.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MinVR.dir/all' failed
make[1]: *** [CMakeFiles/MinVR.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dankeefe** [comment]
There is also a problem compiling on Windows (I'm using VS 2010).  I think it might be related because the trace also leads to the std c++ <utility> include file.  Here's the output I'm seeing:

1>------ Build started: Project: MinVR, Configuration: Debug Win32 ------
1>Build started 12/10/17 2:21:48 PM.
1>InitializeBuildStatus:
1>  Touching "MinVR.dir\Debug\MinVR.unsuccessfulbuild".
1>CustomBuild:
1>  All outputs are up-to-date.
1>ClCompile:
1>  VRDataIndex.cpp
1>C:\Users\keefe\G\src\MinVR\src\main/VRError.h(117): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\string.h(105) : see declaration of 'strcpy'
1>c:\users\keefe\g\src\minvr\src\config\VRDatum.h(367): warning C4244: 'return' : conversion from 'int' to 'MinVR::VRFloat', possible loss of data
1>c:\users\keefe\g\src\minvr\src\config\VRDatum.h(380): warning C4244: 'return' : conversion from 'float' to 'MinVR::VRInt', possible loss of data
1>..\src\config\VRDataIndex.cpp(241): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdio.h(325) : see declaration of 'sscanf'
1>..\src\config\VRDataIndex.cpp(248): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdio.h(325) : see declaration of 'sscanf'
1>..\src\config\VRDataIndex.cpp(268): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdio.h(325) : see declaration of 'sscanf'
1>..\src\config\VRDataIndex.cpp(286): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdio.h(325) : see declaration of 'sscanf'
1>..\src\config\VRDataIndex.cpp(520): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data
1>..\src\config\VRDataIndex.cpp(537): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
1>..\src\config\VRDataIndex.cpp(1042): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdlib.h(433) : see declaration of 'getenv'
1>..\src\config\VRDataIndex.cpp(1046): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdlib.h(433) : see declaration of 'getenv'
1>c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\utility(163): error C2664: 'MinVR::VRDatumPtr::VRDatumPtr(MinVR::VRDatum *)' : cannot convert parameter 1 from 'int' to 'MinVR::VRDatum *'
1>          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
1>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\utility(247) : see reference to function template instantiation 'std::_Pair_base<_Ty1,_Ty2>::_Pair_base<std::string&,_Ty>(_Other1,_Other2 &&)' being compiled
1>          with
1>          [
1>              _Ty1=const std::string,
1>              _Ty2=MinVR::VRDatumPtr,
1>              _Ty=int,
1>              _Other1=std::string &,
1>              _Other2=int
1>          ]
1>          c:\users\keefe\g\src\minvr\src\config\VRDataIndex.h(1272) : see reference to function template instantiation 'std::pair<_Ty1,_Ty2>::pair<std::string&,int>(_Other1,_Other2 &&)' being compiled
1>          with
1>          [
1>              _Ty1=const std::string,
1>              _Ty2=MinVR::VRDatumPtr,
1>              _Other1=std::string &,
1>              _Other2=int
1>          ]
1>          ..\src\config\VRDataIndex.cpp(1108) : see reference to function template instantiation 'std::string MinVR::VRDataIndex::addDataSpecialized<MinVR::VRInt,VRCORETYPE_INT>(const std::string,T)' being compiled
1>          with
1>          [
1>              T=MinVR::VRInt
1>          ]
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:01.04

**Comment by tsgouros** [comment]
I think this is caused by a few lines that I inadvertently left in the VRDataQueue.h after an experiment with an iterator for the VRDataQueue. I came up with an easier way to make an iterator, and neglected to remove those lines. I think you can safely delete the include lines from 23 to 26, but let me know if I'm wrong. I would do it myself, but someone changed the cmake requirements to 3.9 and I can't seem to test the build now until I upgrade my cmake.

**Comment by dankeefe** [comment]
Thanks for the quick response!  This fixed the linux build, but the windows build is still producing the error noted in my second post above.

c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\utility(163): error C2664: 'MinVR::VRDatumPtr::VRDatumPtr(MinVR::VRDatum *)' : cannot convert parameter 1 from 'int' to 'MinVR::VRDatum *'

**Comment by tsgouros** [comment]
Not sure I get where in the code it's pointing to from the reprinted error message. Can you do some interpretation for me? What lines are the problems?

From what little I can tell it seems to be choking on a call to AddDataSpecialized(). I don't get why it should care about that at this point, but are you trying to call it with a pointer? I set up getValue() to return a pointer, but I didn't do that with addData.

**Comment by dankeefe** [comment]
The problem is on line 1272 of VRDataIndex.h, which is:

    std::pair<VRDataMap::iterator, bool>res =
      _theIndex.insert(VRDataMap::value_type(fixedValName, NULL));

Windows needs the NULL to be cast to the expected pointer type like this:

    std::pair<VRDataMap::iterator, bool>res =
      _theIndex.insert(VRDataMap::value_type(fixedValName, (VRDatumPtr)NULL));

That makes it compile at least...  does this look ok to you?

**Comment by tsgouros** [comment]
So it needs to know what *kind* of NULL it is? Sure, whatever.

Compiles ok and all the tests pass on Mac with that change. Sure, go ahead.

**Comment by tsgouros** [comment]
Think this is fixed.
