### ISSUE TITLE
Config design discussion

### ISSUE THREAD

**Issue by dtorban** [ivlab/MinVR2#21]
Hey Team,

An example config file is already sourced in MinVR here:
https://github.com/ivlab/MinVR2/blob/master/apps/server/devices-example.xml

Perhaps this can be a place to come up with a good config design, using this one above as a starting place.

Thanks,
Dan

**Comment by dankeefe** [comment]
I think our major questions on this were about the keynames:  Server, VRPlugins, VRInputDevices, etc..  Should we set this up so we have 3 or 4 special XML tags that VRMain::initialize() looks for when it starts up?

**Comment by tsgouros** [comment]
Yes, I'd think so. How else could they be found? 

It's ok to build a general and abstract framework, and I think there's tremendous value in doing things that way, but you have to get particular at some point, or else you have something that only works in the abstract...

I think all of these things should work that way: there are special names they recognize and data with those names is easy to deal with. And there are procedures for figuring out what to do when you don't recognize the names.
