### ISSUE TITLE
VRDataQueue timer on Windows seems funny

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#223]
The VRDataQueue timer test is failing on Windows. The data queue is supposed to be sorted by time, and dequeue operations are supposed to go in reverse time order. The test of that is failing, presumably because of some misuse of the Windows timer. I'm not a Windows guy, so it is probably something I've done wrong in that department.

This is related to issue #116 which says the queue timer should be the same as the timer used elsewhere in the code. This will require that timer to be re-written slightly to make it available to others. Assigning this to Bret, he can reassign if others seem better suited.

**Comment by tsgouros** [comment]
The test code indicates what order the items in the test queue should be dequeued in an array called "expectedOrder".

This refers to tests 5 and 6 in dataqueuetest.cpp.

**Comment by bretjackson** [comment]
Should the timestamps be able to be consistent across machines in a network? If so, we should be using GetSystemTimePreciseAsFileTime which reports in UTC for windows.

**Comment by tsgouros** [comment]
On the linux and mac sides the time stamp is provided by gettimeofday() which I do not believe is synchronized among machines on a network. However, the whole point of queueing events with a time stamp is so multiple machines can contribute to the same queue and still provide an absolute ordering to the events, so probably we should be doing that.  

There's a makeTimeStamp() method in VRDataQueue.cpp that, well, makes a time stamp.
