### ISSUE TITLE
Build issue with cmake -- seems like VRAppLauncher.h is not yet committed to master?

### ISSUE THREAD

**Issue by willemsn** [ivlab/MinVR2#232]
CMake Error at src/CMakeLists.txt:246 (add_library):
  Cannot find source file:

    ......./MinVR/src/main/VRAppLauncher.h

**Comment by tsgouros** [comment]
VRAppLauncher.h was actually removed from master, but not from the CMakeLists.txt file (oops). I will submit a pull request to fix this, but we are all using the beta branch now, and will advance that to be the master branch in a few days. We recommend you use that branch for now.

**Comment by willemsn** [comment]
Thanks!  I'll switch to beta.

**Comment by tsgouros** [comment]
Addressed with pull request #233
