### ISSUE TITLE
is this right in VRPN::VRVRPNButtonDevice.cpp?

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#236]
Not sure about the structure of the event generation code. But I think there is a problem in the VRPN button events, which seem always to be named "name". Line 108, reads:

```
void VRVRPNButtonDevice::sendEvent(int buttonNumber, bool down)
{
    std::string name = getEventName(buttonNumber);
    if (down) {
        name = name + "_Down";
    }
    else {
 	name = name + "_Up";
    }
    VRDataIndex di = VRButtonEvent::createValidDataIndex("name", down);
    _pendingEvents.push_back(di);
}

```
Shouldn't line 108 read name not "name"?

    VRDataIndex di = VRButtonEvent::createValidDataIndex(name, down);

**Comment by dankeefe** [comment]
Yes, can you please just fix it.


---
Daniel Keefe, Ph.D.
Associate Professor
Department of Computer Science & Engineering
University of Minnesota
www.cs.umn.edu/~keefe

**Comment by tsgouros** [comment]
It's in pull request #237, awaiting review. Thanks!
