### ISSUE TITLE
Option to Suppress CMake Configure Error

### ISSUE THREAD

**Issue by dtorban** [ivlab/MinVR2#238]
In the Macro AutoBuild_check_status in cmake/AutoBuild.cmake it forces two configure steps.  It would be nice there was an option to suppress this error if the user knows exactly what they want.

Perhaps it could be something like -DSUPPRESS_CONFIGURE_ERROR=ON or something similar.

The use case is for build automation using the ExternalProject option in CMake.  If we try to build MinVR as an ExternalProject it causes Visual Studio to wait forever, and the user doesn't know what is going on because Visual Studio gives a generic build error, not the AutoBuild error.

**Comment by dankeefe** [comment]
I think this already exists in the form of the AUTOBUILD_EXECUTE_NOW=ON
option, which is there to support nightly builds and scripting --
situations where the user knows what they want and can enter the options
directly on the command line right away.  If this is set, then AutoBuild
will go ahead and execute right away the first time configure is run, which
is not what you want when using cmake-gui, but is what you want if you are
using the command line and already know what options to set.  See if this
works for you... should be more details / documentation in the top of the
MinVR/cmake/AutoBuild.cmake file.

D


---
Daniel Keefe, Ph.D.
Associate Professor
Department of Computer Science & Engineering
University of Minnesota
www.cs.umn.edu/~keefe

**Comment by dtorban** [comment]
Awesome!  That's what I was looking for.  Thanks.
