### ISSUE TITLE
New rule: When a sample program works, leave it working.

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#25]
More than that, if you change the function of a sample program, leave tracks so the rest of us understand what changed.  The VRMain test program in tests/adapt/adapted.cpp seems not to work for me in the way I'd expected, and I don't really understand what changed.

I think what changed is some aspect of the VRDisplay stuff that I haven't spent time to understand yet, but my plan was to work on the networking, and now I can't do that without spending time on display issues first. Please leave explanations behind when you change working stuff. Thanks.

**Comment by tsgouros** [comment]
Looking further into this, I think it was the result of some of the editing of VRMain, creating the dependency on VRPlugin, and changing some default behavior. At least I think so. This just speaks to the need for getting some tests in place so people can know when they have changed things in a way that needs to be accommodated.

**Comment by dtorban** [comment]
I think we need some kind of automation to make tests work well.
Unfortunately the core functionality is a bit in flux.  I thought I tested
the adapted.cpp functionality, sorry.

Thanks,
Dan

**Comment by dtorban** [comment]
The adapted example works again for Linux and Mac.

**Comment by tsgouros** [comment]
Thanks Dan!
