### ISSUE TITLE
Cmake-gui autobuild issue with Windows builds

### ISSUE THREAD

**Issue by jonovotny** [ivlab/MinVR2#252]
The latest versions of Cmake-gui (Windows) have problems with the MinVR autobuild process. Newer versions of Cmake-gui have an additional dropdown menu to select the target platform for the Visual Studio generator (32/64). The problem is that selecting 64-bit as target in the MinVR cmake project does not propagate to external builds, and externals like Glew are built as 32-bit libraries (I assume that the new dropdown resets to 32-bit between different build steps). This seems to be an issue introduced by the latest cmake app, but it will prevent users from building MinVR so we need to at least tell potential users about the issue. (cmake 3.10.2, does not have the issue yet)

**Comment by Danielwbolson** [comment]
Resolved by commit 951517c85b155b0e6cc691d19f2da3989f5f03d8
