### ISSUE TITLE
Missing return value

### ISSUE THREAD

**Issue by michaelmurphybrown** [ivlab/MinVR2#31]
In VRDisplayFrameAction.h, the following function on lines 61-65 has no return value.

template<class T>
bool SpecificVRDisplayFrameAction<T>::exec()
{
    (obj->*method)();
}

There is a similar function in VRDisplayAction.h on lines 61-65 that has a void return type.

**Comment by dtorban** [comment]
Closed with the following commit:
https://github.com/ivlab/MinVR2/commit/182e3ea2ca18a4e7a5f92c45f866f5df51575ffe
