### ISSUE TITLE
Use interface instead of raw function pointers

### ISSUE THREAD

**Issue by michaelmurphybrown** [ivlab/MinVR2#32]
I'm building my own server-client project based off of "adapt" and I noticed that I have to pass raw function pointers to VRMain for the various callbacks. It seems like a better design would be to provide an interface from which users of MinVR can derive.

The interface will have event, render, and swap member functions implemented by the user's derived class. This will eliminate the repeated code pattern, and also provide more flexibility than raw function pointers (as derived classes can have state, which raw function pointers cannot). Because this uses idiomatic C++, this should also make it easier to integrate with existing systems.

VRMain's initialize function should get rolled into the constructor, which should also take the user's implementation of the interface as an argument. As it stands, the VRMain class is in an indeterminate form after construction, which is an antipattern in C++.  The shutdown method should go in the destructor for the same reason.

These changes would capitalize on C++'s RAII idiom, so resources (memory, network stuff) will be harder to leak.

If you want a global VRMain, you can just use a singleton pattern. No need to code against the grain.

**Comment by dtorban** [comment]
Michael,

Please review example application here (I think this may be more flexible in terms of using plugins and dynamic displays):
[https://github.com/ivlab/MinVR2/blob/master/apps/example/main.cpp](https://github.com/ivlab/MinVR2/blob/master/apps/example/main.cpp)

Documentation on how to run is in the README:
[https://github.com/ivlab/MinVR2/blob/master/README.md](https://github.com/ivlab/MinVR2/blob/master/README.md)

Here are a few points about the example application (some related to what you mentioned):
- Is derived from adapt to be more flexible.
- It can as both a client and a server (no need for separate server application).
- It allows for multi-threaded windowing systems.
- It allows you to configure your displays however you would like and as many as you like (including opening them up as separate processes on linux an mac).  This works by just calling a different config file.
- Callbacks can be dynamic class interfaces, member functions, or function pointers (see [VRRenderer](https://github.com/ivlab/MinVR2/blob/master/display/VRRenderer.h) class).  This allows a user to work with objects or function pointers.  Though I do like the way you suggested.
- Allows you to control your own loop.
- Is not necessarily dependent on any graphics implementation like GLUT, GLFW, OpenGL, etc... (since it uses plugins)

Other Items:
- I tend to shy away from singleton classes because they seem less flexible, but we have gone back and forth on that one.  At one time it was a singleton, which is probably why initialize and shutdown exist.  They could probably be rolled up into the constructor and destructor.
- I really like the idea of having the callbacks as a class interface instead of function pointers.  That is the way MinVR1 is coded, and it works really nicely.

**Comment by michaelmurphybrown** [comment]
Hi Dan,

Thanks for the big response!

I've actually already gone through apps/example/main.cpp. I originally
tried modifying it to work with my project, although Tom suggested that I
try building something from the ground up and sticking MinVR in as I went,
as it'd be more like the process other people would use. He thought it'd be
good to have a guinea pig go through and ask all the dumb questions, so
here I am haha.

On singletons: There is a comment in VRMain.h that reads:

 // 1. The first step is to initialize MinVR. This is a separate
// step from the constructor because it is frequently convenient for
// your VRMain to be a global variable, and C++ does not allow a
// convenient and reliable way to initialize global variables with
// arguments.

My (nebulous) comment about singletons/global variables was about this
comment, which is not true - C++ does in fact have easy ways to do this.
Following from that, we wouldn't have a reason to break the C++ idioms.

In your opinion, would it be logistically possible to change from function
pointers to a class interface? I don't know how much code that would break,
although it doesn't seem like there'd have to be much refactoring anyway.
People using raw function pointers can just turn them into a class, and
people with OOP GUI systems (probably everyone) can undo the workarounds
they've got going. If this is so, I can do all the refactoring and send you
a pull request.

Thanks for your help! I'm excited to get my stuff working in the YURT :D

On Wed, Feb 17, 2016 at 12:26 AM, dtorban notifications@github.com wrote:

> Michael,
> 
> Please review example application here (I think this may be more flexible
> in terms of using plugins and dynamic displays):
> https://github.com/ivlab/MinVR2/blob/master/apps/example/main.cpp
> 
> Documentation on how to run is in the README:
> https://github.com/ivlab/MinVR2/blob/master/README.md
> 
> Here are a few points about the example application (some related to what
> you mentioned):
> - Is derived from adapt to be more flexible.
> - It can as both a client and a server (no need for separate server
>   application).
> - It allows you to configure your displays however you would like and
>   as many as you like (including opening them up as separate processes on
>   linux an mac). This works by just calling a different config file.
> - Callbacks can be dynamic class interfaces, member functions, or
>   function pointers (see VRRenderer
>   https://github.com/ivlab/MinVR2/blob/master/display/VRRenderer.h
>   class). This allows a user to work with objects or function pointers.
>   Though I do like the way you suggested.
> - Allows you to control your own loop.
> - Is not necessarily dependent on any graphics implementation like
>   GLUT, GLFW, OpenGL, etc... (since it uses plugins)
> 
> Other Items:
> - I tend to shy away from singleton classes because they seem less
>   flexible, but we have gone back and forth on that one. At one time it was a
>   singleton, which is probably why initialize and shutdown exist. They could
>   probably be rolled up into the constructor and destructor.
> - I really like the idea of having the callbacks as a class interface
>   instead of function pointers. That is the way MinVR1 is coded, and it works
>   really nicely.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ivlab/MinVR2/issues/32#issuecomment-185032132.

## 

Michael Murphy
BSc Applied Math / Computer Science '15
MSc Computer Science '16
Brown University

**Comment by dtorban** [comment]
Hey Michael,

Cool, sounds like fun.  Rendering already supports sending in a class interface rather than function pointers.  Just do the following:

```
class MyConcreteRenderer : VRRenderer
{
  void render(VRRenderState& state)
  {
     // render code
  }
}

....

// Create concrete renderer object
MyConcreteRenderer myRenderer;

// Get display device and call render
VRDisplayDevice* display = VRMain->getDisplay();
display->render(myRenderer);
```

It is super simple to do.  You could even have multiple different types or renderers, so you can render on the display as many functions as you want without having to specify a callback.  For example:

```
// Create concrete renderer object
MyDefaultRenderer myRenderer;
MySpecialRenderer mySpecialRenderer;

// Get display device and call render
VRDisplayDevice* display = VRMain->getDisplay();
if (doSomethingSpecial) {
  display->render(mySpecialRenderer);
}
else {
  display->render(myRenderer);
}
```

Let me know if this is what you had in mind.

Thanks,
Dan

**Comment by michaelmurphybrown** [comment]
Hi Dan,

Thanks for the help. What's the difference between
VRMain::registerRenderCallback(...) and this method of setting the renderer
you proposed?

My understanding is that you give the callbacks to VRMain and then call
synchronizeAndProcessEvents() and renderEverywhere() in your main loop.
VRMain.cpp calls the raw function pointer callbacks in these methods. How
does manually calling the display's render function affect VRMain's
renderEverywhere functionality / remove the need to set a render callback?

Thanks!

On Wed, Feb 17, 2016 at 11:29 AM, dtorban notifications@github.com wrote:

> Hey Michael,
> 
> Cool, sounds like fun. Rendering already supports sending in a class
> interface rather than function pointers. Just do the following:
> 
> class MyConcreteRenderer : VRRenderer
> {
>   void render(VRRenderState& state)
>   {
>      // render code
>   }
> }
> 
> ....
> 
> // Create concrete renderer object
> MyConcreteRenderer myRenderer;
> 
> // Get display device and call render
> VRDisplayDevice\* display = VRMain->getDisplay();
> display->render(myRenderer);
> 
> It is super simple to do. You could even have multiple different types or
> renderers, so you can render on the display as many functions as you want
> without having to specify a callback. For example:
> 
> // Create concrete renderer object
> MyDefaultRenderer myRenderer;
> MySpecialRenderer mySpecialRenderer;
> 
> // Get display device and call render
> VRDisplayDevice\* display = VRMain->getDisplay();
> if (doSomethingSpecial) {
>   display->render(mySpecialRenderer);
> }
> else {
>   display->render(myRenderer);
> }
> 
> Let me know if this is what you had in mind.
> 
> Thanks,
> Dan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ivlab/MinVR2/issues/32#issuecomment-185284391.

## 

Michael Murphy
BSc Applied Math / Computer Science '15
MSc Computer Science '16
Brown University

**Comment by dtorban** [comment]
Actually the current MinVR2 is still in flux, so this is something we are still discussing as a team.  Perhaps we will talk about this on Friday.  I am proposing that we call render in a different way than registering a callback.  VRMain has a pointer to the display.  The display may be a simple window, or an extremely complex cave like the YURT.   MinVR will abstract out all of the complexity and just give you a display.  As far as we are concerned, it is a simple window.  Then you tell the display to render what you want to render by passing in a VRRenderer.

This allows you to control your own loop.  For example, I am working on a particle system which processes many particles while the previous frame is being rendered, so I need control of starting the rendering and finishing the rendering.  Here is some example code:

```
// main loop
while (true) {
  // start rendering
  display->startRendering(myRenderer);
  // process events for the next frame
  synchronizeAndProcessEvents();
  // do something expensive
  calculateParticles();
  // Finish rendering
  display->finishRendering();
  // synchronize all clients
  mvr->renderEverywhere();
  // swap buffers
  display->swapBuffers();
}
```

This way, I can asynchronously render and compute the next frame at the same time.
- display->startRendering() could send all the commands to the GPUs and call glFlush(). 
- display->finishRendering() could sync up the threaded displays and call glFinish().
- display->swapBuffers() will swap the buffers.

With this approach you don't need to register callbacks for rendering.  You pretty much just tell the display what you want it to render.  I'm just proposing that it is understandable, easy to use, and very flexible.  It also speeds up processing by handling events and rendering (on the graphics card) at the same time.

We still call renderEverywhere().  I forgot to include that in my previous example.  Sorry about that.  Let me know what you guys think.

**Comment by tsgouros** [comment]
Closing this, because it's been discussed and there don't seem to be any outstanding actions necessary.
