### ISSUE TITLE
-std=c++11 does not appear to be a supported gcc option

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#33]
This is on a linux box, gcc 4.4.7 (20120313).

 -Tom

**Comment by dtorban** [comment]
Where do we require -sdt=c++11?  Currently only the threading plugin has that dependency I think.  If so, we can always go without threading.  which project is not building?

**Comment by tsgouros** [comment]
I think it was that one. I also think the gcc I'm using supports many c++11 features, but it spells the option differently. I think it's gnu++0x or something until v4.7 and c++11 after.

**Comment by dtorban** [comment]
Good find.  I was able to reproduce.  I'll add in some logic to ignore that library for now if it requires c++11.

**Comment by tsgouros** [comment]
I'd rather not ignore the library, but use the appropriate option. I fixed it by adding a check for the gcc compiler version to the Linux section of the CMakeLists.txt file in contrib/plugins/Threading.  All works perfectly now, for me.
