### ISSUE TITLE
std::string back is only available for c++11

### ISSUE THREAD

**Issue by dtorban** [ivlab/MinVR2#40]
Getting this error:

/home/dan/src/MinVR2/src/config/VRDataIndex.cpp:129:14: error: ‘VRString’ has no member named ‘back’
     if (elem.back() == '\') {
              ^
/home/dan/src/MinVR2/src/config/VRDataIndex.cpp:131:12: error: ‘VRString’ has no member named ‘back’
       elem.back() = separator;

Apparently back in std::string is only available for c++11.  Is there another way to implement this code?

Thanks,
Dan

**Comment by tsgouros** [comment]
Yes, there is, and I just did it. Should be fine now. Checked into master.
