### ISSUE TITLE
Testcase for detailed performance of DataIndex

### ISSUE THREAD

**Issue by BenKnorlein** [ivlab/MinVR2#47]
I just made a quick test for some performance of addData for the DataIndex. I attached a file with the results in microseconds.

At the moment it takes an average of 0.1 miliseconds to add a new entry to the dataIndex. It seem it is faster when the values is already present (0.025 miliseconds). That means depending on how many values we add this might result in quite a delay, e.g. if we add 30 values this results in 3 miliseconds. Depending on where and how it is setup, this might slow down things quite strong.  In addition this does only take the addData into acount and not the serialization or the push pop states. I suggest we write a detailed example program testing all the calls and see if we can improve performance.

Ben 

[measure.txt](https://github.com/ivlab/MinVR2/files/359609/measure.txt)

**Comment by tsgouros** [comment]
Can you add the code you used for the timing or something to help interpret those numbers? Do you have numbers for the getData() calls, too?

There are tests written for all the data index calls, in the tests directory. But I'll get on it.

The push/pop thing involves extensive cheating, so only values that change actually get pushed or popped.

**Comment by BenKnorlein** [comment]
It was just a hack. And it was windows specific, so not sure if it helps you. It basically just measures the time inside addData

**Comment by BenKnorlein** [comment]
[VRDataIndex.txt](https://github.com/ivlab/MinVR2/files/359872/VRDataIndex.txt)

**Comment by tsgouros** [comment]
Ok, then give me a little more to go on when I'm trying to read that file. Why are the timings so different on the odd and even lines? Were you asking to add something deep in the name hierarchy, or at the root level? What does it mean when a VRDoubleArray is followed by a VRContainer? Where are you getting .1mS and .025 mS? Just put the code here so I can understand what this file is telling me because without it it's not telling me much at all. Thanks.

**Comment by BenKnorlein** [comment]
I did put the code there

**Comment by BenKnorlein** [comment]
Here a more detailed comment:

I ran the desktopSideBySide.xml with the SimpleOpenGL example. The times 
are simply written inside the addData calls. Check the VRDataIndex.txt. 
I could not attach a cpp file, so i had to change to txt.

The order is just how in the Renderloop values are added to the 
dataIndex. The type just tells you which addData call it was. I assumed 
the lower times are when the same value is overwritten as this happens 
several times during rendering.

And it is just a quick hack as i wrote earlier. I think a detailed 
example would be better.

Ben

**Comment by tsgouros** [comment]
I meant the calling program. There is information I can use in the differences between the times, but it is not useable information if I don't know what the caller was doing. But it's ok, I'll figure out something.

**Comment by BenKnorlein** [comment]
Calling program was SimpleOpenGL with the config for desktopSideBySide.xml

**Comment by tsgouros** [comment]
A test case already exists for the data index. It's in the config tests. Closing this issue.
