### ISSUE TITLE
VRDatumPtr does not allow Multithreading

### ISSUE THREAD

**Issue by dtorban** [ivlab/MinVR2#59]
The referenced counted smart pointer to the VRDatum type does not allow threading.  My understanding is it keeps track of a VRDatum type, for example ints, strings, doubles, etc...  When a value is added to any data index, the type pointer reference count is increased and when a value is removed from the data index, the counter is decreased.

The problem is that in threading, items can be added and removed from any data index at any time, so the reference counter gets messed up.  Here is an example of what I think might be going on:
1. VRDataIndex d1 is created on thread 1
2. VRDataIndex d2 is created on thread 2
3. d1.add(intVal) adds VRInt typeVRDatum reference count.
4. d2.add(intVal) starts the add for VRInt type, but does not increase the reference count
5. delete d1 - decrements the reference count and deletes VRInt type
6. d2.add(intVal) increases the reference count of a null value
7. d2.getValue(intVal) - tries to access the VRInt type

I also may not completely understand what is going on for the reference counted type. 

Possible fixes:
- Do not share VRDatumPtr values across VRDataIndex objects.  Then each thread can have its own VRDataIndex object and there is no problem because the VRDatumPtr types are specific to each VRDataIndex.
- Do something different than saving the types with a referenced counted pointer.  Perhaps we could just have a dictionary of supported config types that is loaded at the beginning before any threads are created.  I don't understand the use case enough to make a recommendation.
- Add thread synchronization every time that we add or get something from the VRDataIndex.  I think this would be too much overhead, and could probably slow down everything as you would have to lock at each entry into the data index, even if it was completely independent.
- Don't allow multithreading - Current state, but probably not desirable.
- Don't use the VRDataIndex when using multithreading - It would be nice to use the VRDataIndex here to be consistent with the rest of the framework.
- Other ideas?

**Comment by tsgouros** [comment]
Bummer. Yes, this is for memory management of those objects. The VRDatumPtr object _is_ half of the data index. That is, the index is a correspondence between names and VRDatumPtr objects. I'll have to think about this, and probably talk with you about threading.

**Comment by dtorban** [comment]
Fixed this by making a new VRDataIndex for each thread.  Perhaps when I first reported this issue I didn't rebuild the project... oops.  Appears to work well now without adding the atomic or c++11 dependency.  Woohoo!
