### ISSUE TITLE
convertible containers

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#6]
The VRDatum "Convertible*" classes should probably include a "ConvertibleContainer" class, so that some complicated C++ object can be converted to a VRDatum Container object.  So, for example, a 3D matrix object might consist of a vector of data values, and x, y, and z dimensions. This would then convert to a container:

 <3dmatrix>
  <x>3</x><y>4</y><z>2</z>
  <data>1,2,3,4,5,6,7,etc </data>
</3dmatrix>

**Comment by tsgouros** [comment]
I notice that my careful illustration of how the XML tags would look was eliminated in the save. I guess you can't type XML in these windows. Let me assure you it was a compelling and very convincing illustration, now lost to the world.

**Comment by dankeefe** [comment]
Now I understand what you mean. This would be awesome.

On Friday, December 11, 2015, tsgouros notifications@github.com wrote:

> The VRDatum "Convertible*" classes should probably include a
> "ConvertibleContainer" class, so that some complicated C++ object can be
> converted to a VRDatum Container object. So, for example, a 3D matrix
> object might consist of a vector of data values, and x, y, and z
> dimensions. This would then convert to a container:
> 
> <3dmatrix>
> 342
> 1,2,3,4,5,6,7,etc
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ivlab/MinVR2/issues/6.

## 

Daniel Keefe
Associate Professor
Department of Computer Science and Engineering
University of Minnesota
http://www.cs.umn.edu/~keefe/

**Comment by tsgouros** [comment]
Added a convertible container class. Nobody uses it yet, but it's there. The change is in the pull request queue.
