### ISSUE TITLE
Where do files get installed?

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#66]
For linux, we can default to /usr/local and make it configurable so that we can install them in a module on our gpfs file system. But where do the python bindings go, and can someone list in this issue the appropriate targets for Windows and the Mac-native way to package a library for OS X? (Is /usr/local good enough?)

**Comment by dtorban** [comment]
Just FYI... The current default install location is in build/install and the user can override by setting -DCMAKE_INSTALL_PREFIX=/usr/local.  Not sure if this is what we want to keep, but just letting you know what exists right now:

if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    set (CMAKE_INSTALL_PREFIX "${${PROJECT_NAME}_SOURCE_DIR}/build/install" CACHE PATH "default install path" FORCE )
endif()

**Comment by tsgouros** [comment]
Added install support for the overall library and include files, so closing this for now.
