### ISSUE TITLE
Terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by dtorban** [ivlab/MinVR2#67]
It looks like there is an error in the latest MinVR which may be related to VRDataIndex performance improvements as the commit [ec873c6ddf85c3807026024501a4525538485191](https://github.com/ivlab/MinVR2/commit/ec873c6ddf85c3807026024501a4525538485191) still works.

Running the following will reproduce the error:
../../build/bin/SimpleOpenGL desktop.xml

**Here is the stacktrace:**

0  0x00007ffff56cb035 in __GI_raise (sig=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
1  0x00007ffff56ce79b in __GI_abort () at abort.c:91
2  0x00007ffff601ad1d in __gnu_cxx::__verbose_terminate_handler ()
    at ../../../../gcc-4.5.2/libstdc++-v3/libsupc++/vterminate.cc:93
3  0x00007ffff6018f36 in __cxxabiv1::__terminate (handler=<optimized out>)
    at ../../../../gcc-4.5.2/libstdc++-v3/libsupc++/eh_terminate.cc:39
4  0x00007ffff6018f63 in std::terminate ()
    at ../../../../gcc-4.5.2/libstdc++-v3/libsupc++/eh_terminate.cc:49
5  0x00007ffff601906e in __cxxabiv1::__cxa_throw (obj=<optimized out>, 
    tinfo=<optimized out>, dest=<optimized out>)
    at ../../../../gcc-4.5.2/libstdc++-v3/libsupc++/eh_throw.cc:83
6  0x00007ffff5fc6a4b in std::__throw_length_error (__s=<optimized out>)
    at ../../../../gcc-4.5.2/libstdc++-v3/src/functexcept.cc:74
7  0x00007ffff5ffe882 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()
   from /soft/gcc-4.5.2/ubuntuamd1/lib64/libstdc++.so.6
8  0x000000000045ddde in std::string::_S_construct<__gnu_cxx::__normal_iterator<char const*, std::string> > (__beg=73 'I', __end=-115 '\215', __a=...)
    at /soft/gcc-4.5.2/ubuntuamd1/lib/gcc/x86_64-unknown-linux-gnu/4.5.2/../../../../../include/c++/4.5.2/bits/basic_string.tcc:138
9  0x000000000045b7f1 in std::string::_S_construct_aux<__gnu_cxx::__normal_iter
ator<char const*, std::string> > (__beg=73 'I', __end=-115 '\215', __a=...)
    at /soft/gcc-4.5.2/ubuntuamd1/lib/gcc/x86_64-unknown-linux-gnu/4.5.2/../../../../../include/c++/4.5.2/bits/basic_string.h:1649
10 0x000000000045856f in std::string::_S_construct<__gnu_cxx::__normal_iterator<char const*, std::string> > (__beg=73 'I', __end=-115 '\215', __a=...)
    at /soft/gcc-4.5.2/ubuntuamd1/lib/gcc/x86_64-unknown-linux-gnu/4.5.2/../../../../../include/c++/4.5.2/bits/basic_string.h:1670
11 0x000000000045398d in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<__gnu_cxx::__normal_iterator<char const*, std::basic_string<char> > > (this=0x7fffffffd5b0, __beg=73 'I', __end=-115 '\215', 
    __a=...)
    at /soft/gcc-4.5.2/ubuntuamd1/lib/gcc/x86_64-unknown-linux-gnu/4.5.2/../../../../../include/c++/4.5.2/bits/basic_string.tcc:229
12 0x000000000044c301 in VRDataIndex::getNameSpace (this=0x7fffffffd730, 
    fullName="InitRender")
    at /project/keefe01/vis/sw/user-checkouts/dtorban/src/MinVR2/src/config/VRDataIndex.cpp:590
13 0x0000000000453d89 in VRDataIndex::addDataSpecialized<int, (VRCORETYPE_ID)1> (this=0x7fffffffd730, valName="InitRender", value=1)
    at /project/keefe01/vis/sw/user-checkouts/dtorban/src/MinVR2/src/config/VRDataIndex.h:314
14 0x000000000044e493 in VRDataIndex::addData (this=0x7fffffffd730, valName=
taIndex.cpp:590
13 0x0000000000453d89 in VRDataIndex::addDataSpecialized<int, (VRCORETYPE_ID)1> (this=0x7fffffffd730, valName="InitRender", value=1)
    at /project/keefe01/vis/sw/user-checkouts/dtorban/src/MinVR2/src/config/VRDataIndex.h:314
14 0x000000000044e493 in VRDataIndex::addData (this=0x7fffffffd730, valName=
---Type <return> to continue, or q <return> to quit---
    "InitRender", value=1)
    at /project/keefe01/vis/sw/user-checkouts/dtorban/src/MinVR2/src/config/VRDataIndex.cpp:933
15 0x00000000004707ac in MinVR::VRMain::renderOnAllDisplays (this=0x6f7450)
    at /project/keefe01/vis/sw/user-checkouts/dtorban/src/MinVR2/src/main/VRMain.cpp:508
16 0x0000000000446f18 in MinVR::VRMain::mainloop (this=0x6f7450)
    at /project/keefe01/vis/sw/user-checkouts/dtorban/src/MinVR2/src/main/VRMain.h:71
17 0x0000000000448a5a in MyVRApp::run (this=0x7fffffffd8e0)
    at /project/keefe01/vis/sw/user-checkouts/dtorban/src/MinVR2/examples/SimpleOpenGL/vrexample.cpp:312
18 0x0000000000446c25 in main (argc=2, argv=0x7fffffffda28)
    at /project/keefe01/vis/sw/user-checkouts/dtorban/src/MinVR2/examples/SimpleOpenGL/vrexample.cpp:327

**Comment by tsgouros** [comment]
Addressed issue, my apologies. Fixed in 444f620

P.s. It would be great if it didn't matter what directory was the default when running example/SimpleOpenGL.
