### ISSUE TITLE
Why does SimpleOpenGL execution depend on the default directory?

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#68]
And this is presumably also the case for other executables?

This should not be the case. What do we need to do to fix this?

**Comment by BenKnorlein** [comment]
Not sure. If i understand that issue. You mean because of the libraries? There should be an option to set the default library path in the config-file.

**Comment by tsgouros** [comment]
Someone needs to implement this in such a way that the example programs work by default. It is not a good situation if the example programs fail out of the box with no explanation why. Can we establish a search path and implement that?

**Comment by dtorban** [comment]
Hey Tom,

I can re-implement this functionality.  At one time it used the install
directory as the default search path.  It should be pretty easy.

Thanks,
Dan

**Comment by dankeefe** [comment]
1. Add an error message if MinVR is started without a config file.
2. Add an error message if attempting to load a plugin that cannot be found on the filesystem.  (Check to make sure this is already there.)
3. New standard:  an environment variable called $MINVR_ROOT can be set to determined the root of the MinVR install directory.  Plugins by convention are stored inside $MINVR_ROOT/plugins/*.  When loading a plugin, here is the procedure:

First, check the path specified in the config file for plugin.so.
Second, check the current working directory for the plugin.so.
Third, check the current path/plugins for the plugin.so.
Fourth, check $MINVR_ROOT/plugins

**Comment by dtorban** [comment]
This has been fixed with #78

**Comment by dtorban** [comment]
This issue can be closed.

**Comment by tsgouros** [comment]
Closing, not sure why it wasn't closed before.
