### ISSUE TITLE
root-level Makefile -- do we need?

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#7]
What does the root level Makefile do for us? I find that I edit it frequently to keep it from introducing errors to my build. Is it necessary? I get that it allows both the release and the debug builds to coexist, but I'm not sure why that's an advantage.

**Comment by dtorban** [comment]
Tom, what is causing you errors for building?  The Makefile makes it easy to configure CMake, but not necessary for using CMake.  Also, it is used often for linux build (i.e. make opt -j8, etc...)

**Comment by tsgouros** [comment]
I use a Mac, but I don't use Xcode on it, just the command-line tools. So the Makefile wouldn't build without Xcode, so I had to disable that. And then I was trying to build across multiple directories, but the dependencies didn't work with the Makefile in the way. So I deleted the Makefile and everything is happier now.

The Makefile provides some useful functionality, but you're only using it as a script that accepts arguments.  There are no dependencies recorded in it, which was the whole point behind Makefiles. Why not just write a little shell script called build.sh or something and get out of cmake's way?  Let cmake use the "Makefile" name.

**Comment by dtorban** [comment]
Good idea, I can look into that.  Just out of curiosity, what do you mean by building across multiple directories?  Just want to understand the problem better.  I don't understand why there would be a cmake conflict.

**Comment by BenKnorlein** [comment]
I am also not sure if we gain much from the makefile as it seems to duplicate functionality from cmake. The biggest advantage i see is that it unifies where people put their build (but i am not sure if we have to restrict them). Apart from that i do not see much advantage, but even more disadvantages, e.g. cmake is an easy way to see what options are available and to allow different IDEs. This might be important when different plugins are integrated and should be selectable. (And as you generate with cmake makefiles on Linux you can still use -j8 etc)

**Comment by dtorban** [comment]
I removed the Makefile, so now we should build everything through CMake.  Here are the directions:
- Create build directory:

```
mkdir build
```
- Linux / Makefile

```
cd build
cmake ..
make
```
- Mac / XCode

```
cd build
cmake .. -G xcode
# Build with XCode
```
- Windows

```
# Open up CMake GUI and configure
# Build with Visual Studio
```

**Comment by dankeefe** [comment]
A script of some sort might be a good way of documenting these steps if nothing else.  The Makefile was probably motivated by me through my training from David Laidlaw, following his mantra that you should be able to go into any directory, type "make all", and have it work.  This mantra predates a system like cmake though, so it is fine with me to revisit that.  

Is there any way to write a script like "build.sh" but that would work on linux, OSX, and Windows?  Or, is it necessary to have at least a build.sh and build.bat?  

I think we've committed at this point to having cmake as a dependency, but would be good if we do not have to add "make" or "sh" as dependencies on windows unless they already come packaged with cmake.  We normally install all of these on our computers anyway, so it doesn't matter too much for our lab, but it might be important to others.

**Comment by dankeefe** [comment]
I think this is resolved now with instructions in README.
