### ISSUE TITLE
namespace MinVR

### ISSUE THREAD

**Issue by BenKnorlein** [ivlab/MinVR2#71]

**Comment by tsgouros** [comment]
Need to choose whether to have a namespace consistent across the files, or to have names like "VRDataIndex". Please enter opinions about which we prefer here.

I added the namespace to the dataindex, net, math code. All seems to work. But the namespace is too long: "MinVR" (suggest MVR), and is redundant with names like "VRMain" and "VRDataIndex". Let's do one or the other but not both. Opinions here, please.

**Comment by tsgouros** [comment]
Namespaces added in version e2ec277 .

**Comment by dankeefe** [comment]
Namespace = good, let's use one.  I'm ok with MVR if that is generally preferred.  I don't see a problem with having both a namespace and starting class names with VR*.  Some of our classes (e.g., Main, InputDevice, Factory) are names that might show up in other programs.  Of course they can be disambiguated with MVR:: but sometimes this is annoying and people prefer to just be able to say using namespace MVR.  For example, in the past we had VRG3D::Event and G3D::Event and I thought the code got pretty ugly having to write the namespace in front of Event all the time.

**Comment by tsgouros** [comment]
Closing this, since namespaces were added a while back.
