### ISSUE TITLE
command line flexibility

### ISSUE THREAD

**Issue by dankeefe** [ivlab/MinVR2#73]
Right now, we impose a format for the command line arguments, which is pretty annoying.  It would be nice if we could just leave this up to users.  The reason we impose the format now is in order to support something like forking to start new processes with specific settings on Windows, which does not have a fork() system call.  

We should think more about whether there is another way to support this forking behavior on windows that doesn't require taking over the command line.

**Comment by dtorban** [comment]
Hey Team,

I have a solution to this problem which appears to work pretty well.  I made the change on my commandLine branch here:

https://github.com/dtorban/MinVR2/commit/f7265d9139c1de462466c9e34bc2cf2a905dfb27

I added a new abstract class called [VRAppLauncher](https://github.com/dtorban/MinVR2/blob/commandLine/src/main/VRAppLauncher.h) (which has two methods and acts as a translation layer between MinVR and our own custom applications):

``` c++
class VRAppLauncher {
public:
    virtual ~VRAppLauncher() {}

    // Generates the command line if necessary
    virtual std::string generateCommandLine(const std::string& initString) const = 0;

    // Produces the MinVR specific command line
    virtual const std::string& getInitString() const = 0;
};
```

To use it (for advanced users) you can instantiate your own launcher and pass it into a different VRMain initialize function.  Below is an example where the config filename is actually the 3rd parameter, and other app parameters are dynamically set:

``` c++
std::string minVRCommandLine = std::string(argv[3]) + " /My/ConfigVal1=1 /VRSetupToStart=FrontWall";
VRDefaultAppLauncher launcher(argc, argv, minVRCommandLine);
_vrMain->initialize(launcher);
```

Of course you can create your own launchers, but the [VRDefaultAppLauncher](https://github.com/dtorban/MinVR2/blob/commandLine/src/main/impl/VRDefaultAppLauncher.h) can solve most problems.  What it does is use base64 encoding to pass the values through the command line as MinVRData=....  On the other side it can decode the string and use it just like before.  Here is an example of what it would look like over ssh: 

``` bash
../../build/Release/bin/SimpleOpenGL desktop-local.xml /My/ConfigVal1=1 /VRSetupToStart=FrontWall MINVR_DATA=ZGVza3RvcC1sb2NhbC54bWwgL015L0NvbmZpZ1ZhbDE9MSAvVlJTZXR1cFRvU3RhcnQ9RnJvbnRXYWxsIFZSU2V0dXBzVG9TdGFydD0vTWluVlIvVlJTZXR1cHMvRGVza3RvcCBTdGFydGVkU1NIPTE=
```

Let me know what you guys think.

Thanks,
Dan

**Comment by dtorban** [comment]
By the way, this works for both ssh and Windows forking.  It seems pretty easy to use.

Thanks,
Dan

**Comment by tsgouros** [comment]
Seems to make sense, but I'm not sure I'm understanding what's in the payload. We'll talk in a few minutes?

**Comment by dtorban** [comment]
Sure, the payload essentially is the encoded MinVR command line specification (like a database connection string or something).  For example:

```
MINVR_DATA=ZGVza3RvcC1sb2NhbC54bWwgL015L0NvbmZpZ1ZhbDE9MSAvVlJTZXR1cFRvU3RhcnQ9RnJvbnRXYWxsIFZSU2V0dXBzVG9TdGFydD0vTWluVlIvVlJTZXR1cHMvRGVza3RvcCBTdGFydGVkU1NIPTE=
```

decodes to:

```
MINVR_DATA="desktop-local.xml /My/ConfigVal1=1 /VRSetupToStart=FrontWall VRSetupsToStart=/MinVR/VRSetups/Desktop StartedSSH=1"
```

**Comment by tsgouros** [comment]
Thanks. What's the value of the base64 encoding?

**Comment by dtorban** [comment]
This is so that the MinVR data that is passed via SSH or windows command line is self-contained and does not have any spaces.  This way it won't interfere with the custom application command line.
