### ISSUE TITLE
error out if plugin not found

### ISSUE THREAD

**Issue by dankeefe** [ivlab/MinVR2#75]
We discussed this on 10/7 and determined that the right place to do this error checking is in the VRFactory, when you try to create a plugin, give an error message if the type is not available and then quit.

Once this is working, consider for the future:  Specify in the config file whether the type is required.  Maybe revisit in the future.  

But, Ben and Dan really like this idea, so if they want to add a flag for optional plugins that is ok with me.

**Comment by dtorban** [comment]
Same as #96
