### ISSUE TITLE
please document launcher

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#79]
Can you add some comments about the launcher thing? 

Also, do we still need this version of initialize? Is the arg list redundant?

void VRMain::initialize(int argc, char **argv, const std::string& configFile, std::vector<std::string> args) {

**Comment by dtorban** [comment]
Hey Tom, this is fixed with the Plugin search path pull request.  I added documentation there.  Also, yes, the method you mentioned is an easy way to allow you to completely customize the command line parameters.  Here is the interface and the documentation:

``` c++
  /// If a user wants more control of the command line, this initialize method is the one
  /// that should be used.  Here a user can provide any set of command line arguments in any order.
  /// The only required item that also needs to be passed is the configFile path.  Optionally, a
  /// user can also provide data index overrides in the format "/path/to/item=value".
  void initialize(int argc, char **argv, const std::string& configFile, std::vector<std::string> dataIndexOverrides = std::vector<std::string>());
```

**Comment by dtorban** [comment]
This is done with #78.  This issue can be closed.
