### ISSUE TITLE
Move creating the standard MinVR "ElapsedTime" / "StartFrame" event to VRMain.cpp

### ISSUE THREAD

**Issue by dankeefe** [ivlab/MinVR2#90]
Right now, an event is created once each new frame that holds a double data field for the elapsed time in seconds since the program started up.  A couple of our example programs depend on this.  I think it's a fine idea to have an elapsed time event that gets generated once per frame as part of MinVR, but if application programmers are going to depend on this, then the event should be created within the core of MinVR rather than in a plugin to avoid the possibility of some future plugin authors forgetting to create this important event or calling it by a different name, etc.

I think the reason it is not part of VRMain now is that it is implemented using getGLFWTime() -- moving it to VRMain is not completely trivial because we would need our own system call for getting the current time that works across Windows, OSX, Linux etc.

**Comment by dtorban** [comment]
Would it be easy to add a getTime() in the window toolkit?  It seems like a simple solution.  Perhaps we could create a VRSystemToolkit with system related calls like getTime() or file system calls..

**Comment by dankeefe** [comment]
Adding a getTime() to the window toolkit might be the best solution, at least for short term.  Down the road, if we find that there are a few other items that are similar to getTime, then we could create a SystemToolkit, but at this point it seems like way too much overhead to make it a toolkit for just the one function.  Alternatively, if we come across a windowing framework that doesn't support cross-platform timing info, then we could at that point bump the getTime functionality into the core of MinVR and write our own version.  It looks like GLUT also provides some time-related functions, so maybe it's a pretty common thing for windowing toolkits that operate cross-platform.

**Comment by dtorban** [comment]
Looks like creating a cross platform time like GLFW seems easy enough.  I'll take a stab at it.

**Comment by dtorban** [comment]
Here is G3D code for cross platform system and time calls:

https://sourceforge.net/p/g3d/code/HEAD/tree/G3D10/G3D.lib/source/System.cpp

Should be pretty easy to use.
